#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process if it is running

pid=$(pgrep -f "4-to_infinity_and_beyond")

if [[ -n $pid ]]; then
    kill "$pid"
    echo "4-to_infinity_and_beyond process (PID: $pid) has been stopped."
else
    echo "4-to_infinity_and_beyond process not found."
fi
