#!/usr/bin/env bash
# This script displays all active IPv4 addresses on the machine it's executed on

# Using `hostname -I` to list IP addresses without the interface names, followed by filtering IPv4 addresses
# with `awk` and removing empty lines.
hostname -I | awk '{for(i=1;i<=NF;i++) if ($i ~ /^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$/) print $i}'
