#!/usr/bin/env bash
# Install Apache, create the "Hello ALX" page, and start Apache

# Install Apache
apt-get update
apt-get install apache2 -y

# Create the HTML page with the message
echo "Hello ALX" > /var/www/html/index.html

# Start Apache service
service apache2 start
