#!/usr/bin/env bash
# This script creates an RSA key pair named school with 4096 bits, protected by the passphrase betty
echo "Creating RSA key pair..."
ssh-keygen -t rsa -b 4096 -f ./school -N betty

if [ -f "./school" ]; then
  echo "RSA key pair created successfully."
else
  echo "Failed to create RSA key pair."
fi

